- hosts: all
  become: yes
  vars:
    jenkins_version: "2.289.2"
    jenkins_port: 8080
    jenkins_install_via: "yum"
    jenkins_auth: none
    jenkins_config_owner: jenkins
    jenkins_config_group: jenkins
    jenkins_plugins:
      - git
      - blueocean
  roles:
    - ansible-jenkins